version: "3.3"

services:
  protime-bot:
    container_name: protime_bot
    image: jannes-io/protime-bot
    build:
      context: .
    restart: always
    volumes:
      - ./config.json:/usr/src/app/config.json
